config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "myportfolios#index"

  resources :myportfolios, only: [:index]
  resources :projects, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      post :sort
    end
  end
  resources :stacks, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      post :sort
    end
  end

  get "myportfolios/awwwardsone", to: "myportfolios#awwwardsone"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/myportfolio.rb
class Myportfolio < ApplicationRecord
  has_many :projects
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validates :title, presence: true
  validates :photo, presence: true
  validates :url, presence: true
end

app/models/stack.rb
class Stack < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validates :name, presence: true
  validates :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
  has_many :stacks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/myportfolios_controller.rb
class MyportfoliosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :awwwardsone]
  before_action :set_user, only: :awwwardsone

  def index
    @projects = Project.all
    @stacks = Stack.all

    if user_signed_in?
      @user = current_user
      @projects = @user.projects.order(:position)
      @stacks = @user.stacks.order(:position)
    else
      @projects = @projects.order(:position)
      @stacks = @stacks.order(:position)
    end

  end

  def carousel
  end

  def awwwardsone
  end

  private

  def set_user
    if user_signed_in?
      @user = current_user
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:create, :sort]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.position = @user.projects.length + 1
    @project.user = current_user
    if @project.save
      redirect_to myportfolios_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to myportfolios_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project.destroy
    redirect_to myportfolios_path
  end

  def sort
    @user = current_user

    @project_sorted = params[:projectOrdered].split(",").map{ |id| Project.find(id.to_i) }

    @project_sorted.each_with_index do |p, index|
      p.position = index + 1
      p.save
    end
  end

  private

  def project_params
    params.require(:project).permit(:photo, :title, :description, :url)
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/controllers/stacks_controller.rb
class StacksController < ApplicationController
  before_action :set_stack, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:create, :sort]

  def new
    @stack = Stack.new
  end

  def create
    @stack = Stack.new(stack_params)
    @stack.position = @user.stacks.length + 1
    @stack.user = current_user

    if @stack.save
      redirect_to myportfolios_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @stack.update(stack_params)
      redirect_to myportfolios_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @stack.destroy
    redirect_to myportfolios_path
  end

  def sort
    @stack_sorted = params[:stackOrdered].split(",").map{ |id| Stack.find(id.to_i) }

    @stack_sorted.each_with_index do |s, index|
      s.position = index + 1
      s.save
    end
  end

  private

  def stack_params
    params.require(:stack).permit(:name, :photo, :user_id)
  end

  def set_stack
    @stack = Stack.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/myportfolios_helper.rb
module MyportfoliosHelper
end

app/helpers/myportofolios_helper.rb
module MyportofoliosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/stacks_helper.rb
module StacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arnaud Rigourd | Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>">
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:image" content="<%= meta_image %>">
    <meta property="og:description" content="<%= meta_description %>">
    <meta property="og:site_name" content="<%= meta_title %>">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%#= favicon_link_tag "favicon.ico", rel: "icon", type: "image/png" %>
    <%= render 'shared/ios_pwa_links' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <!-- Hotjar Tracking Code for Portfolio -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:3352199,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>
  </head>

  <% if params[:action] == "awwwardsone" %>
    <body class="container__awwwardsone">
  <% else %>
    <body data-controller="navbar">
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/myportfolios/awwwardsone.html.erb
<div  data-controller="body" data-body-target="body">
  <div class="image-track" data-body-target="imageTrack" data-mouse-down-at="0" data-prev-percentage="0">
    <img class="image" src="https://images.unsplash.com/photo-1673361654018-0a7f27d8fa05?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80" alt="pic" draggable='false' data-body-target="image" />
    <img class="image" src="https://images.unsplash.com/photo-1673284175200-cd6714555968?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80" alt="pic" draggable='false' data-body-target="image" />
    <img class="image" src="https://images.unsplash.com/photo-1673488680322-1becb786d3f1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1856&q=80" alt="pic" draggable='false' data-body-target="image" />
    <img class="image" src="https://images.unsplash.com/photo-1673468810663-aadc745ab561?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1771&q=80" alt="pic" draggable='false' data-body-target="image" />
    <img class="image" src="https://images.unsplash.com/photo-1673232120601-a898f2a19d39?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1772&q=80" alt="pic" draggable='false' data-body-target="image" />
    <img class="image" src="https://images.unsplash.com/photo-1673495249492-52c9c8122872?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80" alt="pic" draggable='false' data-body-target="image" />
    <img class="image" src="https://images.unsplash.com/photo-1673557964587-dd88a344e4ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80" alt="pic" draggable='false' data-body-target="image" />
    <img class="image" src="https://images.unsplash.com/photo-1673269234098-b737ce7d7948?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2215&q=80" alt="pic" draggable='false' data-body-target="image" />
  </div>
</div>

app/views/myportfolios/index.html.erb
<nav data-navbar-target="navbar" >
  <p><a href="#top">ARNAUD RIGOURD</a></p>

  <p id="log">
    <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete} %>
    <% else %>
      <%= link_to "log in", new_user_session_path %>
    <% end %>
  </p>

  <div class="toggle-menu hidden" data-controller="toggle-menu" data-navbar-target="toggleDiv">
    <i class="fa-solid fa-bars" data-action="click->toggle-menu#toggleAction" data-toggle-menu-target="burgerMenu"></i>
    <div class="dropdown-list hidden" data-toggle-menu-target="dropdownList">
      <ul data-navbar-target="dropdownList">
        <li><a href="#portfolio">PORTFOLIO</a></li>
        <li><a href="#stacks">STACKS</a></li>
        <li><a href="#about-me">ABOUT ME</a></li>
        <li><a href="#contact">CONTACT</a></li>
      </ul>
    </div>
  </div>

  <div class="nav-list">
    <ul>
      <li><a href="#portfolio">PORTFOLIO</a></li>
      <li><a href="#stacks">STACKS</a></li>
      <li><a href="#about-me">ABOUT ME</a></li>
      <li><a href="#contact">CONTACT</a></li>
    </ul>
  </div>
</nav>

<div class="wrapper" data-navbar-target="wrapper" data-action="scroll->navbar#updateNavbar">

  <header>

    <div class="header__image" id="top">
      <h1><strong>ARNAUD RIGOURD</strong></h1>
      <h3><strong>Full Stack Developer</strong></h3>
    </div>

    <div class="header__scroll">
      <p><a href="#portfolio">SCROLL TO DISROVER</a></p>
      <p>|</p>
    </div>
  </header>

  <%# <span id="portfolio"></span> %>

  <div class="main-wrapper">
    <main>
      <div id="portfolio" class="container__portfolio">
        <h3>PORTOFLIO</h3>

        <p>Here are some personal and professional projects I’d like to share with you.</p>

        <% if user_signed_in? %>
          <div class="projects" data-controller="sortable-projects" data-sortable-projects-sort-url-value="<%= sort_projects_path %>">
        <% else %>
          <div class="projects">
        <% end %>
          <% @projects.each do |p| %>
            <div class="project", style="background-image: url('<%= cl_image_path p.photo.key %>')" data-sortable-projects-target="project", data-project-id= <%= p.id %>>
              <%= link_to "https://#{p.url}", target:"_blank" do %>
                <div class="project-title" >
                  <p><%= p.title.upcase %></p>
                  <p><%= p.description %></p>
                </div>
              <% end %>

              <% if user_signed_in? %>
                <div class="project-man">
                  <p><%= link_to "Edit", edit_project_path(p) %></p>
                  <p><%= link_to "Delete", project_path(p), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
                </div>
              <% end %>
            </div>
          <% end %>

          <% if user_signed_in? %>
            <%= link_to new_project_path, class:"new-btn" do %>
              <i class="fa-solid fa-plus"></i>
            <% end %>
          <% end %>

        </div>
      </div>

      <%# <span id="stacks"></span> %>

      <div id="stacks" class="container__stacks">
        <h3>STACKS</h3>

        <% if user_signed_in? %>
          <div class="stacks" data-controller="sortable-stacks" data-sortable-stacks-sort-url-value="<%= sort_stacks_path %>">
        <% else %>
          <div class="stacks">
        <% end %>
          <% @stacks.each do |s| %>
            <div class="stack" data-sortable-stacks-target="stack" data-stack-id ="<%= s.id %>" >
              <p><%= cl_image_tag s.photo.key, style:"max-width: 40px; height: 40px", alt:"image" %></p>
              <p class="stack-name"><strong><%= s.name %></strong></p>

              <% if user_signed_in? %>
                <div class="stack-man">
                  <p><%= link_to "Edit", edit_stack_path(s) %></p>
                  <p><%= link_to "Delete", stack_path(s), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
                </div>
              <% end %>
            </div>
          <% end %>

          <% if user_signed_in? %>
            <%= link_to new_stack_path, class:"new-btn" do %>
              <i class="fa-solid fa-plus"></i>
            <% end %>
          <% end %>
        </div>
      </div>

      <%# <span id="about-me"></span> %>

      <div id="about-me" class="container__about-me">
        <h3>ABOUT ME</h3>

        <p>Hello! My name is <strong>Arnaud Rigourd</strong>, and I am a 28-year-old junior <strong>full stack developer</strong> with a strong background in business and finance. I received my education at ESC Rennes School of Business, where I studied business administration, and later pursued a master's degree in finance.</p>
        <br />
        <p>After completing my studies, I began my career as a relationship manager at a leading French bank. However, I wanted to challenge myself with new opportunities and expand my horizons, which led me to return to school at <em>Le Wagon Paris</em> to study <strong>Web Development</strong>.</p>
        <br />
        <p>As a junior <strong>developer</strong>, I am now seeking <strong>freelance</strong> missions or a full-time job to further develop my skills and work with companies on their <em>digitalization strategy</em>. I am particularly interested in working with companies that value personalization and customization, as I believe that a company's values should be reflected in their <em>website</em>.</p>
        <br />
        <p>I am a strong believer in teamwork and have developed this skill through my studies and previous experiences. I am also an ambitious and fast learner who enjoys taking on new challenges, as demonstrated by my career choices. If you are looking for a reliable and motivated collaborator on your next project, please do not hesitate to contact me 😊</p>
      </div>

    </main>
  </div>

  <footer>
    <h3 id="contact">CONTACT</h3>

    <div class="container__contact">
      <div class="container__contact--info">
        <a href="https://www.linkedin.com/in/arnaudrigourd/"><i class="fa-brands fa-linkedin"></i></a>
        <p>LINKEDIN</p>
        <p><a href="https://www.linkedin.com/in/arnaudrigourd/" target="_blank">@arnaudrigourd</a></p>
      </div>

      <div class="container__contact--info">
        <i class="fa-solid fa-envelope"></i>
        <p>EMAIL</p>
        <p><a href="mailto:arnaud.rigourd@hotmail.fr">arnaud.rigourd@hotmail.fr</a></p>
      </div>

      <div class="container__contact--info">
        <a href="https://github.com/Arnaud-Rigourd"><i class="fa-brands fa-square-github"></i></a>
        <p>GITHUB</p>
        <p><a href="https://github.com/Arnaud-Rigourd" target="_blank">@Arnaud-Rigourd</a></p>
      </div>
    </div>
  </footer>
</div>

app/views/projects/edit.html.erb
<%= render partial:"shared/form_project", locals: {project: @project} %>

app/views/projects/new.html.erb
<%= render partial:"shared/form_project", locals: {project: @project} %>

app/views/shared/_form_project.html.erb
<div class="container__form">
  <%= simple_form_for(project) do |f| %>
    <%= f.input :title %>
    <%= f.input :url %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

<%= link_to "back to home", myportfolios_path %>

app/views/shared/_form_stack.html.erb
<div class="container__form">
  <%= simple_form_for(stack) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

<%= link_to "back to home", myportfolios_path %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/stacks/edit.html.erb
<%= render partial:"shared/form_stack", locals: {stack: @stack} %>

app/views/stacks/new.html.erb
<%= render partial:"shared/form_stack", locals: {stack: @stack} %>